let parse = require('@babel/parser').parse;
let generate = require("@babel/generator").default;
let traverse = require("@babel/traverse").default;
const types = require("@babel/types");
let fs = require('fs');

let js_code = fs.readFileSync("dw.js", "utf-8")

const ast = parse(js_code, {
    sourceType: 'script',
    plugins: ['jsx']
});


const bigarry = [
    "Bf9IDwy",
    "wMvYB1bHzgrPBMC",
    "y3jLyxrL",
    "x2rHDge",
    "zgfYAW",
    "wMy1",
    "B25Nzxn0DxjLzw5K",
    "x2fLrw4",
    "rvy5",
    "x3HMB3jTtw9Kzq",
    "x2LUBMvYswrtDg9Y",
    "Bg9Hza",
    "Bwf4x2nOywLU",
    "DxbuB2TLBG",
    "Cg9W",
    "x2rLDMLJzuLUzM9dB2XSzwn0B3i",
    "y29VA2LLrw5HyMXLza",
    "zMLSzsbLCNjVCG",
    "Dvq4",
    "DgHYB3C",
    "BgfZDf9MBhvZAa",
    "tvntDhjLyw0",
    "BwvTtgv2zwW",
    "DgvTCa",
    "D2L0AenVBNzLCNrLCG",
    "yMXFDhjLzq",
    "zMLSBa",
    "zhLUx3rYzwu",
    "thvJAwrHifnHBNmGvw5Py29Kzq",
    "x19Nq3jxzwi",
    "wM42",
    "AMf2yuvUywjSzwq",
    "x2nVBxbYzxnZ",
    "BMv4Df9VDxq",
    "x3nHDMvuB0fSBa",
    "x3jLDMvYC2vnyxa",
    "tvLssufe",
    "BgvMDa",
    "ywjZ",
    "zgvWDgG",
    "zhjVCa",
    "z2v0v2LUzg93rMvHDhvYzxm",
    "zw1T",
    "x3rYx2LUAxq",
    "t3bLBLntta",
    "teLos19tvefuvvm",
    "zM9UDfnPEMu",
    "CMDIysGXmdiSidiWncWGmcWGmc4Ykq",
    "D19ZAxPL",
    "D2fYBG",
    "qNC4A0zOq0O",
    "Bwf0y2HLCW",
    "q2fUDMfZq2fWDhvYzu1LzgLHu3rYzwfT",
    "l3rVA2vUp3y9ms4WjMu9mszJpte",
    "t00Z",
    "x3jcBg9JAW",
    "qxjPywWGvw5Py29KzsbnuW",
    "tuq1",
    "EhuY",
    "u2PO",
    "sg1Hy1niqtuXmG",
    "Bgv0DgvYu3bHy2LUzW",
    "AxnpCgvU",
    "q09mt1jFqLvgrKvsx0jjva",
    "jNq9mYzZpq",
    "u2vNB2uGuhjPBNq",
    "D29Yzhm",
    "x3j0Aw1L",
    "x0rfq19yrK9stv9nt0rf",
    "s1KX",
    "EvG0",
    "zgv2AwnLugL4zwXsyxrPBW",
    "jNy9mq",
    "AgvHCf9TyxG",
    "yMLUzej1zMzLCG",
    "BMv4Da",
    "z2v0tw91C2vmB2nH",
    "y2XLyxjdB2XVCG",
    "B2jQzwn0u3rVCMu",
    "qMXVy2TdAxbOzxjnB2rL",
    "DMLZAwjPBgL0EwnOyw5Nzq",
    "tw96qxbWzwfYyw5Jzq",
    "zgvMBgf0zuvUza",
    "zxH0CW",
    "rw5JCNLWDg9Y",
    "BxnxCML0zvbYB2zPBgvYtwfYAW",
    "y2XHBxa",
    "D2vIA2L0u3bLzwnOr3jHBw1HCG",
    "DMLZAwjSzq",
    "DM1JztL4BMu",
    "u2HHCMvKv29YA2vY",
    "x2DLDfDLyMDSvMvUzg9Y",
    "uMfIyML0",
    "mI4WlJa",
    "C3rHDgu",
    "x3rYx2zSDxnOx2jSB2nR",
    "z2v0q2HHBM5LBerHDge",
    "v29Yza",
    "C3rYAw5N",
    "ndaXmJq3mJbwre1eqK4",
    "C2f2zvrVsw5KzxHLzercif9RzxKGpsa",
    "yMLFDMfSAwq",
    "ugTJCZC",
    "Bwf4",
    "BeWX",
    "B25fBMq",
    "B2zMC2v0v2LKDgG",
    "tM9qywrKAw5N",
    "z2v0rMLUz2vYChjPBNq",
    "B25TB3vZzw1VDMu",
    "x2LUDLn1yKTLExm",
    "yMXVy2TFC3rHCNq",
    "CMvZB2X2zwrpChrPB25Z",
    "zMqY",
    "BMvLzcbKAwn0Aw9Uyxj5",
    "thvJAwrHifnHBNmGvhLWzxDYAxrLCG",
    "vhjPCgXLrevt",
    "y29SB3i6icm3odu0ndC",
    "x3vYBfn0B3jHz2u",
    "tvmGu2fUCYbtzxjPzG",
    "Aw5UzxjizwLNAhq",
    "D29YzfnWywnPBMC",
    "q291CMLLCIbozxC",
    "yxvM",
    "sg1Hy1niqtm4na",
    "lI96BgLIl2rLzMXHDgu",
    "x2DLDe1LzgLHrgv2AwnLCW",
    "ELK4",
    "x3rYx3n0B3jLzf9IBg9JAW",
    "C2fMyxjP",
    "y2HYB21L",
    "CMfUzg9TC0LK",
    "BNrQ",
    "vKvsvevyx1niqurfuG",
    "yuS4",
    "C2fSDa",
    "Bwf4x2XHENLFBwf0y2G",
    "yMvNAw5qyxrO",
    "C3rHCNrPBwu",
    "tfvdsurbieDsqu5erq",
    "lI9JB21TB24",
    "A2vJ",
    "vu5nqvnlrurFuKvorevsrvjFv0vcr0W",
    "D2vIzhjPDMvY",
    "x2nOzwnRqxv0B2rYAxzLCG",
    "x3rYx2fSAwDU",
    "DxnLCKfNzw50",
    "DgfU",
    "B25ZDwnJzxnZ",
    "C2vYAwy",
    "thvJAwrHieHHBMr3CML0Aw5N",
    "C2nYzwvU",
    "y2zN",
    "x2nPzfn0B3jHz2u",
    "x2HHC2G",
    "zgvMBgf0zvjHDW",
    "zwnT",
    "C3fYDa",
    "Bwf0y2HFC3rHCNq",
    "oKfMzdyJrd0",
    "yxr0ywnOu2HHzgvY",
    "qM9VAYbbBNrPCxvH",
    "CgfKzgLUzW",
    "y29SB3i6icmYmtK1rJi",
    "z2v0vhjHy2vjBMzV",
    "yxn1",
    "oNjvmZy9qfO",
    "zgvMBgf0zvjLC2v0s2vLCa",
    "AhjLzG",
    "tvmGueDVDgHPyW",
    "zNjVBunOyxjdB2rL",
    "revt",
    "Aw5UzxjxAwr0Aa",
    "q2LWAgvYugfYyw1Z",
    "C3rYzwfTigvUza",
    "mdeYmZq1nJC4owfIy2rLzMDOAwPRBg1UB3bXCNn0Dxz3EhL6qujdrevgr0HjsKTmtu5puffsu1rvvLDywvO",
    "q2HYB21PDw0",
    "zM9YBwf0DgvY",
    "x2LZt2S",
    "Bw96sw5KzxHLzerc",
    "cIbHDca",
    "DxbSB2fKvvbeqvrbu2vZC2LVBG",
    "C2LU",
    "x2TLExn0CMvHBq",
    "y2HLy2TtAw11Bgf0Aw9U",
    "D2vIA2L0t2zMBgLUzuf1zgLVq29UDgv4Da",
    "D2LUzg93x3nPEMu",
    "y2XHC3noyw1L",
    "x2nYzwf0zujYB3DZzxjjra",
    "z2v0sLnptG",
    "y2XPzw50wq",
    "Dgv4DerLy29YyxrPB24",
    "z2v0rw5K",
    "q29TAwmGu2fUCW",
    "z2v0u2vZC2LVBKLe",
    "zgvMAw5L",
    "x195yG",
    "uejlreyY",
    "BMLS",
    "C3rHy2S",
    "mZiXmdK2nejcB0jLBq",
    "z2vUzxjHDgu",
    "zgv2AwnLtwvTB3j5",
    "DxnLuhjVz3jHBq",
    "x2DLDfbYB2nLC3neyxrH",
    "tw9UywnV",
    "C3rHDf9KzxnJ",
    "y3vYCMvUDfrPBwu",
    "AM9PBG",
    "q291CMLLCG",
    "CMvTB3zLsxrLBq",
    "lI9HzgXLCJmY",
    "AgvHCa",
    "l3zHBgLKp3y9ms4WjMu9mszJpte",
    "zxHLy3v0zq",
    "u2vNB2uGvuKGu2vTAwjVBgq",
    "vuntAgvSBePHDMe",
    "DxjSx2HVC3q",
    "C3rYyxrLz3K",
    "mtK3yvLkswLL",
    "zgL2",
    "zMLSBfrLEhq",
    "Aw5Zx2G",
    "y2LK",
    "y29UBMvJDgLVBG",
    "DgLTzw91Da",
    "iZa2oq",
    "zgvSDgfy",
    "ugfSyxrPBM8",
    "D2LUzg93qML0CW",
    "z2vVBg9JyxrPB24",
    "x2nYzwf0zuHTywnizwXWzxi",
    "yMvMB3jLDw5SB2fK",
    "zMX1C2G",
    "x2rVuMvZzxq",
    "AgfZAf9TyxnR",
    "yxzHAwXxAwr0Aa",
    "BM90ihn1ChbVCNqGAw5KzxHLzerclG",
    "y2XPy2S",
    "CMvHzezYB21jBMrLEgvKrei",
    "B3bZ",
    "x19JCLDLyG",
    "yxn1mq",
    "Evfe",
    "x25eyxrHqNL0zxm",
    "zwzMzwn0AxzLvhLWzq",
    "mtiXodrcsvD0rxm",
    "x2LlzxK",
    "C2HPzNq",
    "x29lzxK",
    "ywLK",
    "C2vUza",
    "ChjPBNq",
    "q0jd",
    "x2HHC2HLCG",
    "zhvtDg9YywDLswqY",
    "seSZ",
    "r2v0tw91C2u",
    "x2rLDMLJzuTLEq",
    "Bw96sw5Uzxjty3jLzw5y",
    "CMDIkdaSmJu1ldi1nsK",
    "DMfSDwu",
    "BgvUz3rO",
    "Ahr0CdOVlZeYnY4WlJaUmtO1ndm0ns8",
    "x2DLDfrVDwnOu3vWCg9YDa",
    "sfC1",
    "D2LKDgG",
    "zhqY",
    "q29UC29Syxm",
    "BxntzxrjBw1LzgLHDgu",
    "x3bYB2nLC3m",
    "Dg9tDhjPBMC",
    "BxvSDgLWBhK",
    "x2DLDe5LDhDVCMTjBMzV",
    "y29Uy2f0",
    "Ahr0CdOVlZeYnY4WlJaUmtO0mdaWma",
    "rxzLBNq",
    "z2v0svb2nKfKzhjLC3m",
    "z2v0q29UzMLNu3rHCNq",
    "C3vIC3rY",
    "CgvUzgLUz19IDwy",
    "yMLFyNvM",
    "vxrMmty",
    "u0HbmJu2",
    "CMf3",
    "zxH0zw5K",
    "qM9VA21HBIbpBgqGu3r5Bgu",
    "B3jPzw50yxrPB24",
    "runc",
    "v0i5",
    "x3j0Aw1LmG",
    "CMvXDwvZDcbPBMrLEgvKreiGzxjYB3iU",
    "DfOY",
    "CMvSzwfZzq",
    "zgvJCNLWDa",
    "qxjPywWGtMfYCM93",
    "BwvKAwfezxzPy2vZ",
    "vhjLyNvJAgv0ie1t",
    "lI9TzxnZywDLCW",
    "zgLZy29UBMvJDa",
    "A2v5u2L6zq",
    "x2rLrw4",
    "zhvZ",
    "Aw5MB0nHBgXIywnR",
    "xsaTifS",
    "zgvZDgLUyxrPB24",
    "x19JCMvHDg9Y",
    "C2LTCgXLwe9sq2LWAgvY",
    "Aw5ZDwzMAwnPzw50ig1LBw9YEq",
    "vfe2",
    "Ag9YAxPVBNrHBa",
    "CgK5",
    "ChjVDg9JB2W",
    "B251CgDYywrLBMvLzgvK",
    "C29YDa",
    "t0zc",
    "q2XPCgjVyxjK",
    "Axb2nI5ZAhv6AwXTlMnU",
    "CgfRBYbKzwzSyxrLicHMCM9Tie5VzgvJysbWCM9Qzwn0kq",
    "D2vIA2L0uMvXDwvZDezPBgvtExn0zw0",
    "D29YzejYzwfR",
    "Bg93",
    "B3v0Chv0tgvUz3rO",
    "zM9YBwf0",
    "z2v0",
    "C3bSAxq",
    "x2DLDfzHBgLKqNjVD3nLCKLUzM8",
    "D2HPDgvtCgfJzq",
    "AgfZAf9IAxrZ",
    "rwrNzq",
    "rgvJCNLWDg9Y",
    "zgvSDgfz",
    "qMfZzq",
    "Dg9vChbLCKnHC2u",
    "DxbKyxrL",
    "yMXVy2TtAxPL",
    "x3vHAwrjBMzVq29SBgvJDg9Y",
    "zgv0zwn0uhjPDMf0zu1Vzgu",
    "q3vZDg9TrxzLBNq",
    "vwe5",
    "AM05",
    "ywrKrxzLBNrmAxn0zw5LCG",
    "C3bSAwnL",
    "zxH0CMfFyML0CW",
    "AgfZAf9ZAgLMDa",
    "CMfUzg9T",
    "C3rYBq",
    "y2fKza",
    "x2rPy3rFC2v0",
    "zgvMyxvSDhm",
    "y2HLy2TfEhrLBNnPB25Z",
    "AgfZAf9ZAxPL",
    "B25Py2vJyw5KAwrHDgu",
    "x2fLrgu",
    "ywrP",
    "zgvSzxrLrgf0ywjHC2u",
    "DhLWzq",
    "y2XLyxi",
    "txfwvvfHDMe",
    "Dgv4Da",
    "Cg9YDa",
    "x3n0CMLUz1rVvwLUDdHbCNjHEq",
    "vgjjntnTzdy",
    "x21HCa",
    "sw50zxjUzxqGrxHWBg9Yzxi",
    "yNvMmMjPBNn0CMLUzW",
    "qxjPywW",
    "C2XPy2u",
    "C3rV",
    "CNrJugvLCKnVBM5Ly3rPB25Z",
    "DvCZ",
    "z2v0u3rVCMfNzvvWzgf0zxm",
    "BM90ihn1ChbVCNqGz2v0qMf0DgvYEsbbueKU",
    "t3y2",
    "yxbWzw5Kq2HPBgq",
    "mJCWmJG1nNv6t0fIzG",
    "yxnZDMe1",
    "zgvMBgf0zvnLDerPy3rPB25HCNK",
    "DgfUAa",
    "x2rLCZe",
    "DwfPzfrLBgvJB21sDw4",
    "Dg9ymZi",
    "A0GX",
    "zhLUx2r0CMvL",
    "thvJAwrHienHBgXPz3jHCgH5",
    "zgLJDgLVBMfYEq",
    "Cgf0Ag5HBwu",
    "DhjHBNnHy3rPB24GzxjYB3iU",
    "rMLYzwzVEa",
    "CMvTB3zL",
    "C3rYAw5NAwz5",
    "Dgv4DejHC2vSAw5L",
    "ugfZC3DVCMrcyxnLzenPCgHLCG",
    "rMm1",
    "sgvSDMv0AwnH",
    "mJaW",
    "vu5nqvnlrurFvKvore9sx1DfqKDm",
    "u2vYDMLJzvDVCMTLCG",
    "AgfYzhDHCMvdB25JDxjYzw5JEq",
    "refurq",
    "qw5KywXLie1VBM8",
    "DxbSB2fKvvbeqvrb",
    "B250Aw1LB3v0",
    "u2HVy2T3yxzLiezSyxnO",
    "C3r5Bgu",
    "C3rHDgLJx2XLBG",
    "r0vu",
    "BgfIzwW",
    "mZG0mdK2tNvjAfjf",
    "x3f1zxj5vg9Rzw4",
    "zgvZy3jPChrPB24",
    "ChjLDL9Szw5NDgG",
    "q1K4",
    "z2v0u3rHCNq",
    "CgfYC2u",
    "y29SB3i6icngmZqZmZy",
    "Bg9JyxrPB24",
    "y3G0",
    "z2v0uMvXDwvZDeLe",
    "C2vUDa",
    "C3DW",
    "y29TCgLSzvnOywrLCG",
    "zgXH",
    "CMDIkdi1nsWYntuSmcK",
    "AgnYyW",
    "BxnmyxvUy2HvCMK",
    "zgvMBgf0zuLUAxqY",
    "x2HHC0fKqMXVy2S",
    "zg93BMXPBMTnyxG",
    "Dw5PzM9YBtfM",
    "i2y2ma",
    "DxjS",
    "yxnZDMe2",
    "z2v0q29UDgv4Da",
    "x3f1zxj5u2vZC2LVBKLe",
    "DM1JztL4zhe",
    "zgv0zwn0sw5JB2DUAxrVignHBM5VDcbKzxrLCM1PBMuGDgHLigjYB3DZzxi",
    "C3vIyxjYyxK",
    "lI96BgLIl21LC3nHz2vZ",
    "yMXFy291BNq",
    "su5ervHfrercx05btuu",
    "Dvm3",
    "C3rHDgLJx3rYzwu",
    "zw5JCNLWDejSB2nR",
    "yNvMmNn0CMLUzW",
    "zw5J",
    "z2v0vgLTzvzHBhvL",
    "AgLKzgvU",
    "D2vIA2L0ugvYC2LZDgvUDfn0B3jHz2u",
    "z2v0rNvSBfLLyxi",
    "z2v0ugfYyw1LDgvY",
    "BMfTzq",
    "zgvMBgf0zvnLDeHLywrLCG",
    "yNjHDMu",
    "y29SB3i6icaJoefdmJq5",
    "z2v0q2fUDMfZx3q",
    "u2vYAwfSAxPHyMXLq2LWAgvY",
    "Aw5KzxHLzerc",
    "yNvPBgrjra",
    "x195yNjV",
    "pt09pt09pt09pt09pt09pt09pt09pt09pt09pt09pJ4+pG",
    "zgvMBgf0zuLUzM8",
    "rgf0zvrPBwvgB3jTyxq",
    "x2vUvMfSDwu",
    "zgvMBgf0zq",
    "zwyY",
    "C2v0rgvIDwDNzxi",
    "yMrZ",
    "z2v0vMfSAwq",
    "zMLSBfjLy3q",
    "mtHWDcbbCMLHBa",
    "Dg9eyxrHvvjm",
    "vuC0",
    "u2vNB2uGvuKGu3LTyM9S",
    "zfy0",
    "thvJAwrHienVBNnVBgu",
    "A0m3",
    "yMrP",
    "B3b0x2XLBG",
    "qujdrevgr0HjsKTmtu5puffsu1rvvLDywvPHyMnKzwzNAgLQA2XTBM9WCxjZDhv2D3H5EJaXmJm0nty3odKHqcmKjsyQkcLFkY1BxxT9oY48pJ8",
    "Bg9R",
    "qxjPywWGtvq",
    "zM9UDezHBwLSEq",
    "y3jLyxrLt2zMzxi",
    "r3y0",
    "qujdrevgr0HjsKTmtu5puffsu1rvvLDywvPHyMnKzwzNAgLQA2XTBM9WCxjZDhv2D3H5EJaXmJm0nty3odKRlZ0",
    "x3nHDMvpyMPLy3q",
    "yNjVD3nLCKXHBMD1ywDL",
    "y2S5",
    "D2vIA2L0uMvZB2X2zuXVy2fSrMLSzvn5C3rLBvvsta",
    "Aw5Uzxjive1m",
    "y2HLy2TKzxrLy3q",
    "sxnVmtaXmJy",
    "yxjYyxLtzxq",
    "y3jLyxrLqNvMzMvY",
    "q3DTigzQB3jKyMfUAYbNBhLWAhmGDMv4DcbXDwL6lcdWN5Id",
    "zMm5",
    "qw5ZAvG5mJm",
    "x2TLEvbYAw9YuMvZzxq",
    "Aw5SAw5L",
    "Ceq3",
    "vM82",
    "CMf0Aw8",
    "Dhj5CW",
    "Aw5JB21WyxrPyMXLihzLCNnPB24",
    "Bwf0y2HFyxzHAwXHyMXL",
    "Dg90ywXFB3v0",
    "zgeY",
    "Bwf4x2nVzgu",
    "vhCX",
    "x2DLDefl",
    "zNjLCxvLBMn5",
    "DgvZDa",
    "x3n0yxrL",
    "zvK5",
    "D19IAxrZ",
    "y3j5C3rHBa",
    "Aw5JBhvKzxm",
    "q2vUDhvYEq",
    "x3f1zxj5rgv2AwnLsuqY",
    "zhvFD2vIx3nKAW",
    "DgnK",
    "uKm0",
    "BgL0x2j1zNnPEMu",
    "y2fUzgLKyxrL",
    "q1nttw96rg9JDw1LBNrsDwXL",
    "x2DLDeXVy2fSvufjra",
    "x2DLDerLDMLJzuTLEuXPBMTjBMzV",
    "yxzHAwXizwLNAhq",
    "z2v0u2vJB25KCW",
    "yxbWq29Kzu5HBwu",
    "BM90igDLDa",
    "D3jHCa",
    "q2vUDhvYEsbhB3rOAwm",
    "z2v0qNjVD3nLCKLe",
    "sgv4",
    "EtnOyM5Yogq0CZj6DgPIy2eXD2D4AZzTCwT0zJLWEhi",
    "CMv0DxjU",
    "zw5JCNLWDa",
    "lI4VDxrPBhmVy29TBw9U",
    "C2fTC3vUz0fY",
    "Bwf4vg91y2HqB2LUDhm",
    "BgfZDf9SAxq",
    "C2LNqNL0zxm",
    "DgHLBG",
    "Bwf0y2G",
    "ugvYzM9YBwfUy2voyxzPz2f0Aw9UvgLTAw5N",
    "r2vUzxzH",
    "mteXmteX",
    "yNvMzMvYigvYCM9Y",
    "x2XcBg9JAW",
    "CMvHzhLtDgf0zq",
    "BgfUz3vHz2vZ",
    "y3nS",
    "B3v0zxjxAwr0Aa",
    "x2fWAuTLEq",
    "qNvMoa",
    "zhvtDg9YywDLswq",
    "vgLTzxm",
    "z3PPBMrLEa",
    "x19MAxjLzM94x18",
    "BheZ",
    "C2v0",
    "AgfZt3DUuhjVCgvYDhK",
    "x2rLCZi",
    "x3n1yKTLExm",
    "DhjHy2vjBMzV",
    "ywvZrw5JCNLWDa",
    "Dwn3zwi",
    "zxH0CMfFyMfZzq",
    "Bwf4x2XLBMD0Aa",
    "l2LWp3bRzZ0",
    "C2LUAa",
    "Ewj6",
    "yM5K",
    "C2v0q3vZDg9Tsg9ZDa",
    "zgvJCNLWDejSB2nR",
    "AxnqCML2yxrL",
    "CMvKDwnL",
    "Bg9JywXtDg9YywDL",
    "y2HHCKf0",
    "qujdrevgr0HjsKTmtu5puffsu1rvvLDywvPHyMnKzwzNAgLQA2XTBM9WCxjZDhv2D3H5EJaXmJm0nty3odKRlW",
    "A3GX",
    "rMLYzwj1zW",
    "uMfIyML0tgvNywn5",
    "ywjJzgvMz2HPAMTSBw5VChfYC3r1DND4ExO",
    "z2v0rwXLBwvUDej5swq",
    "CMvHzhDYAxrL",
    "CMv2zxjZzq",
    "y29TBwvUDa",
    "tvmGt3v0Bg9VAW",
    "y3j5C3rLBG",
    "B25mAw5L",
    "q29TAwmGu2fUCYbnuW",
    "qKG1",
    "yNL0zuXLBMD0Aa",
    "AwLM",
    "u2iX",
    "q2fUBM90igzPBMqGBw9KDwXLicC",
    "BgfUz3vHz2u",
    "rMC1",
    "BM90ihn1ChbVCNqGBwvKAwfezxzPy2vZiefqss4",
    "x2jHC2u2nfrVqxjYyxLcDwzMzxi",
    "y2XVBMu",
    "vgfOB21H",
    "B3v0Chv0",
    "BxnqB2LUDgvYrw5HyMXLza",
    "C2v0vhLWzwq",
    "khbYzwzLCNmTy29SB3iTC2nOzw1LoIa",
    "wxrJ",
    "C3vIC3rYAw5N",
    "y3jLyxrLuhjVz3jHBq",
    "BwL4sw4",
    "zg9JDw1LBNrfBgvTzw50",
    "zM9UDfn0EwXL",
    "ChvMzMLUrgv2AwnL",
    "w29IAMvJDcbbCNjHEuj1zMzLCL0",
    "BKu0",
    "ugvYzM9YBwfUy2u",
    "BwLU",
    "CMvZDwX0",
    "qNKX",
    "r0OY",
    "z2v0twLSBgLZzwnVBMrZ",
    "x2LUBMvYvgLTzvn0B3i",
    "sgfZAgvY",
    "sg1Hy1jjuevnrde2ma",
    "CMvZzxq",
    "x3nLCNzLCKfJy2vZCW",
    "Aw5MB0y",
    "ChjLDG",
    "x2rLCZm",
    "zgf0zq",
    "zg9Uzq",
    "rhiY",
    "t0C0",
    "uLrdugvLCKnVBM5Ly3rPB24",
    "z2v0t3DUuhjVCgvYDhLoyw1LCW",
    "C2vZC2LVBLn0B3jHz2u",
    "DgLTzvPVBMu",
    "thvJAwrHifnHBNm",
    "yxnPBMG",
    "x2DLDfDLyMDSuMvUzgvYzxi",
    "x2DLDfjPC2TjBMzV",
    "x2nPCgHLCG",
    "yxv0BW",
    "BNz2",
    "zgvIDwC",
    "C3rHDhvZ",
    "z2v0qMf0DgvYEq",
    "x2LWzLn0B3jHz2u",
    "z2v0re5b",
    "BxnnyxHuB3vJAfbVAw50CW",
    "B25VCMLLBNrHDgLVBMnOyw5Nzq",
    "BwvZC2fNzq",
    "Cg9ZAxrPB24",
    "jhn1CgvY",
    "uhjVBwLZzq",
    "t0SZ",
    "u0Hbmq",
    "zNvUy3rPB24",
    "CMvZCg9UC2vuzxH0",
    "zMzA",
    "CMLK",
    "zgv2Dg9VBhnJAgfUz2u",
    "y2jKza",
    "l2XPyI9KzwzSyxrLlMPZ",
    "uhvZAe1HBMfNzxi",
    "x2DLDfrPBwv6B25L",
    "zwy1",
    "ChjVy2vZC0jSB2nR",
    "C2v0tg9JywXezxnJCMLWDgLVBG",
    "ywnVCW",
    "CgXHDgzVCM0",
    "yxnZAwDU",
    "y3jLyxrLt2jQzwn0u3rVCMu",
    "z2v0rwXLBwvUDhncEunSyxnZtMfTzq",
    "qNvMzMvYzwrcBg9JA0fSz29YAxrOBq",
    "vfjjqu5htevFu1rssva",
    "x3nTC1rVA2vUu3rVCMfNzq",
    "AwrK",
    "Dw5Wywq",
    "AgvPz2H0",
    "B3bYDa",
    "yNjVD3nLCMjYyw5K",
    "DwfPzfvUAwnVBvj1BG",
    "yJi5mdCW",
    "ywq1",
    "ywjZB2X1Dgu",
    "Au84",
    "y2LWAgvYDgv4Da",
    "tgf0Aw4X",
    "x3rPBwvtDg9YywDL",
    "BM9Uzq",
    "lI90CMvLCW",
    "CxvLCNLNzxrtDgfYDa",
    "r2v0ugfNzxm",
    "v0vcr0XFzgvIDwDFCMvUzgvYzxjFAw5MBW",
    "EwfUzgv4",
    "y2HLy2TcCM93C2vYAw5MB20",
    "quvt",
    "rgvMBgf0zq",
    "x2nHzgrtDg9YywDL",
    "x2nOzwnRzgv0zwn0CW",
    "D3jPDgu",
    "zNjVBuj5DgvZ",
    "jM5IC3a7",
    "y3jLyxrLq0rjra",
    "z2v0tw9UDgG",
    "EhH4EhH4EhGTEhH4Ec00EhH4lxL4EhGTEhH4EhH4EhH4EhH4",
    "se1bqW",
    "tvq3",
    "rLjbr01ftLrFu0Hbrevs",
    "qvy5",
    "x2DLDefSBeLUzM8",
    "BMLJzv9Szw5NDgG",
    "CMvJDa",
    "C3rYAw5NmMj1zG",
    "x2DLDerLDMLJzuTLEq",
    "yxbWBgu",
    "C2v0sxrLBq",
    "yw1K",
    "CMvTB3zLq2HPBgq",
    "v2LUz2rPBMDZidi",
    "CM91BMq",
    "Ag9ZDg5HBwu",
    "x2DLDfzHBhvLrNjVBufSBa",
    "z2v0twLUDxrLCW",
    "qMXVy2TdAxbOzxi",
    "yNvMzMvY",
    "y3jLyxrLrgf0yunOyw5UzwW",
    "vMvYzgfUyq",
    "q0zc",
    "nZDIAKjQthO",
    "ywvZrw5JCNLWDcbLCNiGx2TLEtOG",
    "B2jQzwn0",
    "DhjLyxn1CMu",
    "u0HbmZG0",
    "B3bLBKrHDgfIyxnL",
    "Dg90ywXFAw4",
    "DgfYz2v0",
    "vLa0",
    "zMXHDhrLBKnODw5RCW",
    "vxrMmtzcrq",
    "q2vUDhvYEsbty2HVB2XIB29R",
    "u2vNB2uGvuKGtgLNAhq",
    "C2X3",
    "A3O0",
    "zgLZCgXHEq",
    "B3v0zxjizwLNAhq",
    "y2XPzw50wa",
    "y29TChv0zq",
    "yMnK",
    "C2HHzgvYu291CMnL",
    "Chv0",
    "zxHWBte",
    "v2vIs2L0twvKAwflzxLZ",
    "Bha3",
    "zxHWB3j0CW",
    "CvmY",
    "lwzJCZaXmq",
    "BxnN",
    "C2v0u21KDMfSDwu",
    "zxHWAxjLCW",
    "y2vPBa",
    "zxzLBNq",
    "tvmGr290AgLJ",
    "D2vIz2W",
    "tvmGuMvMzxjLBMnLifnHBNmGu2vYAwy",
    "C3bHBG",
    "BM93",
    "zMzs",
    "yMfM",
    "CgrMvMLLD2vYrw5HyMXLza",
    "v2LUz2rPBMDZidm",
    "z2v0sw5MBW",
    "q1rs",
    "x2LZt2jQzwn0",
    "C1y1",
    "ywvZrgvJCNLWDcbLCNiGx2TLEtOG",
    "qNvMmty",
    "BfyX",
    "y2HHCMDPBMC",
    "BwvTB3j5",
    "y3jLyxrLu2HHzgvY",
    "B3b0Aw9UCW",
    "DMLZAwjPBgL0Evn0yxrL",
    "rgv2AwnLtw90Aw9UrxzLBNq",
    "BgLUzuHLAwDODa",
    "qujdrevgr0HjsKTmtu5puffsu1rvvLDywvPHyMnKzwzNAgLQA2XTBM9WCxjZDhv2D3H5EJaXmJm0nty3odK",
    "wKGY",
    "tui4",
    "x2DLDg1VDxnLDgvZDa",
    "Bg9VA2fOzwfK",
    "AgvHza",
    "ywXSu2v0DgXLza",
    "Dw1JCJL4Bgu",
    "x2DLDfzHBgLKtMv0D29YA0LUzM8",
    "y29SB3jezxb0Aa",
    "D2vIA2L0",
    "x29IAMvJDfrVsNnVBG",
    "x2LUDKTLEvnJAgvKDwXL",
    "uKm0rhjVCa",
    "y3jLyxrLreLe",
    "lI96BgLIl3PZDhjLyw0",
    "C2f2zvrVsw5KzxHLzerc",
    "BgLI",
    "AxztAxPL",
    "z2v0u2HHzgvYugfYyw1LDgvY",
    "yti5mdCW",
    "B25eyxrH",
    "DMvYDgLJywW",
    "z2v0uhjVz3jHBvbHCMfTzxrLCG",
    "q1fV",
    "yNL0zu9MzNnLDa",
    "yxnZzxj0",
    "q2LWAgvY",
    "zgvMBgf0zuLUAxq",
    "zxrZ",
    "zMfSC2u",
    "x2DLDerLDMLJzuLUzM8",
    "sgvSDMv0AwnHie5LDwu",
    "x19HD2fPDgvY",
    "ue9tva",
    "D2LUzg93",
    "CgfKu3rHCNq",
    "teLorq",
    "x2rVq3j5ChrcBg9JAW",
    "t3bLCMe",
    "Ahr0CdOVl2XVy2fSlMfKC3bVD2vYlM5LDdO1mdmYns8",
    "q2fTyNjPyq",
    "Edy0",
    "zxCX",
    "qNvMmZi",
    "x2DLDeLUDKzYB21bBgW",
    "yxzHAwXFAw4",
    "x3zHBhvL",
    "x2i2nf9KzwnVzgu",
    "DwfPze1VyMLSzvj1BG",
    "x2LWzMXHz1n0B3jHz2u",
    "twfSzM9YBwvKifvurI04igrHDge",
    "AxrLCMf0Aw9UCW",
    "x2nYzwf0zuHLBhbLCG",
    "x2nYzwf0zujYB3DZzxjjrdi",
    "AgrHys5ZAhv6AwXTlMnU",
    "Dgv4DefSAwDU",
    "CMvKDwn0Aw9U",
    "v2LUz2rPBMDZ",
    "rKXpqvq",
    "vw5RBM93BG",
    "A25Lzq",
    "x3bHCNnLu2vYDMLJzurHDge",
    "zMXVB3i",
    "y2fUDMfZ",
    "z3PPCa",
    "Ahr0CdOVlZeYnY4WlJaUmtOZntaWmc8",
    "C2LTDwXHDgvhDwLK",
    "z2v0vxjStwv0Ag9K",
    "qxjPywWGuM91BMrLzcbnvcbcB2XK",
    "B3rOzxi",
    "Aw5JCMvTzw50vMfSDwu",
    "CgvHCMW",
    "D21T",
    "C2f2zvrVsw5KzxHLzercihrYyw5Zif9RzxKGpsa",
    "yxbWtMfTzq",
    "x2nOzwnRvMfSDwu",
    "lI91DgLSCY9JB21TB24",
    "x2rVrMLUywXPEMu",
    "r2vVCMDPyq",
    "D19TyxnR",
    "vgLTzxmGtMv3ifjVBwfU",
    "BMLJzv9TyxrJAa",
    "B3bLBG",
    "zgnK",
    "x2DLDef1zgLVrLa",
    "DgrP",
    "zg93BMXPBMS",
    "Aw5Zzxj0",
    "C3rHCNq",
    "AgvHCf9Szw4",
    "C2LKtMv0u3rHDhvZ",
    "vxrMmtzmrq",
    "EhH4EhH4EhG",
    "sg1Hy1niqtiYna",
    "x19LzgDLvhjHy2TPBMDqCMv2zw50Aw9Uu3rHDgLZDgLJCW",
    "x2TLEvnJAgvKDwXL",
    "DMvUzg9Y",
    "C3rHCNrszw5KzxjPBMC",
    "r29Vz2XL",
    "AuKX",
    "y2XVC2u",
    "zgvI",
    "y29ZAa",
    "y21JAtL4zgu",
    "EwO2",
    "C2v0q29UzMLN",
    "BxnjBMrLEgvKrei",
    "zgD1",
    "q2HLy2Tdyw52yxm",
    "y3jLyxrLt3nJAwXSyxrVCG",
    "Dg9gAxHLza",
    "x0voq19yrK9stv9nt0rf",
    "x2vUDMfSDwu",
    "EeDO",
    "whq0",
    "AgvHzgvY",
    "twLJCM9ZB2z0ifnHBNmGu2vYAwy",
    "tvndu1nnyxrYAxG",
    "kg9IAMvJDcKG",
    "zM9UDa",
    "EvyY",
    "yNvMzMvYrgf0yq",
    "Axe3",
    "A2rM",
    "q2fSAwjYAq",
    "qxvKAw9gudO",
    "zxH0CMe",
    "CNr0",
    "z2v0sw5Uzxjjra",
    "C2vYDMLJzvDVCMTLCG",
    "x2LZt0TjBML0",
    "yxnPBG",
    "Dgv4DfrYyw5ZzM9YBq",
    "Dhj1zq",
    "revcvuC",
    "Dg9vventDhjPBMC",
    "ChvZAa",
    "zMLSBfn0EwXL",
    "ChjLDL9TyxrJAa",
    "z2v0vw5PzM9YBuXVy2f0Aw9U",
    "zu43",
    "C2fUCY1ZzxjPzG",
    "yMLUC3rYAw5NmMj1zG",
    "AgLNAa",
    "t2zMBgLUzuf1zgLVq29UDgv4Da",
    "C3rHBMrHBg9Uzq",
    "x3bYzxzcBg9JAW",
    "qvjsqvLFqLvgrKvs",
    "u2vNB2uGvuK",
    "tw9UB3r5CguGq29YC2L2yq",
    "zgv0zwn0sw5JB2DUAxrVihnVBwvOB3CGzMfPBgvKihrVihf1zxj5ihn0B3jHz2uGCxvVDge6ia",
    "l3jLCg9YDd92pteUmI4WjMu9mszJpteMCJ0",
    "x2LKu3rVCMfNzq",
    "qxvKAw9cDwzMzxi",
    "zMLSDgvY",
    "y2HLy2TPBNrHy3q",
    "z2v0rwXLBwvUDhncEvrHz05HBwu",
    "yMfUyw5H",
    "z2v0sxrLBq",
    "z3POzwfK",
    "jMnHBgXIywnRpq",
    "s24Y",
    "mteYmtq5u3znvLnW",
    "qMfZzty0",
    "Bwf0y2HFBgvUz3rO",
    "y29SB3i6icngrumWmdC",
    "x19Nzw5LCMf0B3i",
    "x3f1zxj5u21Zqxv0AfrVA2vU",
    "zu01",
    "zf9KzxnJ",
    "tguZ",
    "zgvSzxrLu2HHzgvY",
    "D2L0AenYzwrLBNrPywXZ",
    "z2v0vgLTzxPVBMvpzMzZzxq",
    "x2DLDfzHBgLKqwXSsw5MBW",
    "CgvUzgLUz19VDxq",
    "x3f1zxj5rgv2AwnLsuq",
    "DhjPyw5NBgu",
    "Dg9uAw1Lu3rYAw5N",
    "C2v0vMfSDwu",
    "oKfMzdyJrd06qwzKnInepq",
    "C21JBtL4C2u",
    "yxrHBMG",
    "C2rP",
    "Bg9Nmxa",
    "y2HHCKnVzgvbDa",
    "x2DLDejYB3DZzxjjBMzV",
    "Bg9M",
    "CMvUzgvYzwrcDwzMzxi",
    "qMXVyLvsthmGyxjLig5VDcb5zxqGC3vWCg9YDgvK",
    "DgK0",
    "D2vIA2L0twvKAwftDhjLyw0",
    "Bwv0Ag9K",
    "r2vUzxjHDg9YigLZigfSCMvHzhKGzxHLy3v0Aw5NlG",
    "x2fWCgvUza",
    "q2HYB21L",
    "Bwu4",
    "zxzLBM9Kza",
    "s0zW",
    "yxbW",
    "u1rbveLdx0rsqvC",
    "Cg1JAZL4z2u",
    "Cg93",
    "thvJAwrHiezHEa",
    "zgv2",
    "zgf0ysbLCNjVCG",
    "y3jLyxrLrwXLBwvUDa",
    "B2jQzwn0vg9kC29U",
    "u2vNB2uGu2nYAxb0",
    "jwnB",
    "zxHW",
    "zxHWzxjPBwvUDgfSlxDLyMDS",
    "y3jLyxrLtMv3swq",
    "B25JB21WBgv0zq",
    "x2L2",
    "sw50Ba",
    "q09nueLmrv9tvefuvvm",
    "zgy2",
    "zNvUyW",
    "q1rsr2XHzg1HBG",
    "u2fMyxjP",
    "zM9UDfDLAwDODa",
    "ChjPBNrwywX1zq",
    "ANnizwfWu2L6zuXPBwL0",
    "BxntyxzLqMXVyG",
    "BNvTyMvY",
    "CMvWBgfJzq",
    "BgLUzujYzwfR",
    "yxrHBG",
    "C3rYzwfTigvYCM9Y",
    "zgvMBgf0zvjLC2v0",
    "ywnK",
    "x3bRz1n0B3jHz2u",
    "yxzHAwXFB3v0",
    "CgvUzgLUz19IDwzFC2L6zq",
    "l3vUBg9Hzd92pteUms4WjMu9mszJpte",
    "yxr0ywnR",
    "B2uY",
    "qML0C3rYzwfTifzLCMeGu2fUCYbnB25V",
    "r0y5",
    "zMLUywXPEMu",
    "DgHYzxnOB2XK",
    "qMf0DgvYEu1HBMfNzxi",
    "yxjJ",
    "Bg9N",
    "vxrMoa",
    "y3jLyxrLrhLUyw1Py3ndB21WCMvZC29Y",
    "yMLK",
    "CMvHza",
    "ywvZrgvJCNLWDa",
    "Aw5PDa",
    "x2fYCMf5qNvMzMvYvg9cyxnLnJq",
    "ywXWAgfIzxrPyW",
    "qNjHDMu",
    "z29Vzf9TyxrJAa",
    "z2v0vgLTzxn0yw1W",
    "mtfWDcbUBY1YzwfSlwzVBNqTmtiZ",
    "DgLTzq",
    "y2f0y2G",
    "wwrk",
    "lI91DgLSCY9ZDhjPBMDZ",
    "x2rLvMfSDwu",
    "q291BNrLCG",
    "x21KvMfSDwu",
    "B25YzwfKExn0yxrLy2HHBMDL",
    "x2rVuhjVy2vZC0jSB2nR",
    "x2DLDeXVy2fSsw52",
    "zhjHD0fYCMf5CW",
    "qxjPywWGsgvICMv3",
    "y29Z",
    "x2DLDfDLyMDSq2fUDMfZ",
    "y2fSBa",
    "Bwf4x2nOywLUx2XLBMD0Aa",
    "zgLZCgf0y2HfDMvUDa",
    "thvJAwrHiejYAwDODa",
    "q1ntuhjPBwL0AxzLvMfSDwu",
    "x2LUBMvYq2fKzfn0B3i",
    "Bwq1",
    "B25TB3PMDwXSC2nYzwvUy2HHBMDL",
    "Dw5KzwzPBMvK",
    "zw5JB2rL",
    "x2DLDenHBNzHC0zqq29Kzq",
    "z2vUzxjHDgvsyw5KB21tDhjPBMC",
    "zgf0yv90ExbL",
    "yMXFzgvZyW",
    "B25LCNjVCG",
    "CMDIkdi1nsWWldi1nsK",
    "z2v0vg9Rzw5jBMzV",
    "C2v0vgLTzvzHBhvL",
    "x2nOzwnRAw50ywn0CW",
    "Bw9UB3nWywnL",
    "y2H1BMTtAxPL",
    "y3jLyxrLrw5JCNLWDg9Y",
    "x25sB3vUzhm",
    "y2XVC2vqyxrO",
    "A2v5",
    "AgfZx3n0CMvL",
    "Bgv2zwW",
    "Ahr0Chm6lY8",
    "BgLNAhq",
    "BMv4Df9PBG",
    "x2DLDerLDMLJzuTLEuXPBMTjBMzVmG",
    "vgLTzxmGtMv3ifjVBwfUifbt",
    "Dg9mB3DLCKnHC2u",
    "Dg9vCMXtywzLqMfZzty0",
    "sxnVotC5nZe",
    "CgX1z2LUCW",
    "z29Vzf9Szw5NDgG",
    "Bw1TBw1TBw1TBwXSAq",
    "yM9KEq",
    "rMq4",
    "tvLssufeifbstW",
    "DMvYDgv4qxr0CMLIug9PBNrLCG",
    "Aw5KzxHpzG",
    "BM9YBwfS",
    "C3C4",
    "CMyY",
    "AxrLCMf0B3i",
    "u3K2",
    "x3bHCNnL",
    "Dgv4DfnOywrVDW",
    "z2v0vMfSDwu",
    "D2HLzwW",
    "zxjYB3i",
    "x3nLDfvZzxjeyxrHCW",
    "x3rYx3rHBgX5",
    "y2HLCNj5",
    "ywvZrgvJCNLWDcbLCNiGC2vJCMv0oIa",
    "x3n1ChbVCNrgB250CW",
    "sg1Hy1niqte",
    "rxzWs0rg",
    "z2v0u21Zqxv0AfrVA2vU",
    "x2nOzwnRvMfSDwvdreLe",
    "u0HbmW",
    "y29VA2LL",
    "x2LKC3rVCG",
    "BMf2AwDHDg9Y",
    "x2nOzwnRzxH0zw5ZAw9UCW",
    "y29UBMvJDa",
    "zxjY",
    "z2v0vgLTzq",
    "x2TLEq",
    "ExrJ",
    "C2f2zurHDge",
    "z2v0vg9Rzw4",
    "BtLADfjYEJPXDwPuoebKyq",
    "z2v0BgfZDeroqq",
    "q2fTyNjPysbnyxrO",
    "yxvKAw9uAw1LB3v0",
    "x21Vzgu",
    "ANnVBLrVt2jQzwn0",
    "C2v0suruExbL",
    "x2nVDw50zxi",
    "qxbWBgu",
    "rfa1",
    "x2LKsw5MBW",
    "ChjVDg90ExbL",
    "rM5Q",
    "tvmZ",
    "DxrMogjVCMrLCG",
    "mtaXnMznq3nKCG",
    "ywrZyM94",
    "u3rYzwfTq2LWAgvY",
    "z2v0rgf0zq",
    "Ahr0CdOVl2XVy2fSAg9ZDdO1mdiXmY9ZDgf0Dxm",
    "C2f2zvrVsw5KzxHLzercigDLDcbFA2v5id0G",
    "x2DLDejHDhrLCNK",
    "CgL4zwXezxb0Aa",
    "zw5HyMXLvMvYDgv4qxr0CMLIqxjYyxK",
    "v29YzefYCMf5",
    "zhLUx2X0CMvL",
    "zwXLBxm",
    "qxbWBgvqyxLfCNjVCG",
    "lI9JCMmZmG",
    "nZeWmdq5nuPuvgXcEa",
    "mdaWmda",
    "twf0AenHBNzHCW",
    "Bf9KzxnJ",
    "B2zMC2v0sgvPz2H0",
    "C3rHCNrjBML0",
    "DxbSB2fKu21Zqxv0AfrVA2vU",
    "y3jLyxrLtMv3swqY",
    "C2v0vMfSDwvbDfrPBwu",
    "oNjvmZy9qfO6CLuZnJ1awG",
    "zw51BwvYyxrLrgv2AwnLCW",
    "Aw5WDxq",
    "D2vIA2L0vgvTCg9Yyxj5u3rVCMfNzq",
    "z2v0rxH0zw5ZAw9U",
    "AgfZAgvY",
    "sg1Hy01enq",
    "qxjPywWGqMXHy2S",
    "yxr0CMLIDxrLihzLyZiGCdT1BMLMB3jTigzSB2f0ihq7DM9PzcbTywLUkcL7zMXVyxqGCZ1ZAw4ODcK7zMXVyxqGyZ1JB3mODcK7z2XFug9ZAxrPB249DMvJncHWkM1HDdiOyYXZlc1ZlgmPldeSmsK7Fq",
    "x2DLDfzHBgLKrgv2AwnLsw5MBW",
    "zw5Kzwq",
    "ywnVC2G",
    "sw1Wywn0",
    "CgvYzM9YBwfUy2u",
    "CgvUzgLUzW",
    "DM9PzcbTywLUkcL7z2XFrNjHz0nVBg9YpxzLyZqOmsWWldaSmsK7Fq",
    "C2v0rMXHz3m",
    "sg1Hy1niqtm",
    "q09mt1i",
    "zM9YrwfJAa",
    "yxbWBhK",
    "ywXNBW",
    "ugfSyxrPBM8GtgLUB3r5Cgu",
    "uKLqru1emtyW",
    "DwK5",
    "D2vIA2L0sw5KzxHLzerc",
    "ltK5otLWEa",
    "C2LK",
    "Bwf4x2XHENK",
    "z2XVyMfSq29TCg9ZAxrLt3bLCMf0Aw9U",
    "zf9IDwy",
    "DhjHBNnHy3rPB24",
    "AxnjBML0AwfSAxPLza",
    "t0jkrunux1nut1jfx05btuu",
    "y2H1BMTZ",
    "u0HbnteY",
    "C3rYC3rHCNq",
    "CgfK",
    "x21PBKj1zMzLCLnPEMu",
    "nZjWEa",
    "zxrP",
    "yxbWvMvYC2LVBG",
    "Bw9Kzq",
    "CxvLCNLvC2fNzufUzff1B3rH",
    "z2v0sg91CNm",
    "vKq2",
    "C2HYAw5RqNvM",
    "v2C3",
    "tvmGu2vYAwy",
    "sg1Hy1niqti1nG",
    "ywrSzxi",
    "z2v0rw5JCNLWDeTLEq",
    "qKC1",
    "y3jLyxrLrgvJCNLWDg9Y",
    "u0HbmJi0"
];

function a0_0x40fd(_0x412559, _0x3c8930) {
  var _0x5ab0ee = bigarry;
  return (a0_0x40fd = function (_0x12e38a, _0xd109fc) {
    var _0x167b95 = _0x5ab0ee[_0x12e38a -= 0x33dd9 ^ 0x33d6e];
    void (0x83f90 ^ 0x83f90) === a0_0x40fd['HqnvQQ'] && (a0_0x40fd['gMESMf'] = function (_0x8cb1b3) {
      for (var _0xca5a2c, _0x206ef4, _0x10a753 = '', _0x9b3c4 = '', _0x193332 = 0xe5ae4 ^ 0xe5ae4, _0x5ed166 = 0xefed8 ^ 0xefed8; _0x206ef4 = _0x8cb1b3['charAt'](_0x5ed166++); ~_0x206ef4 && (_0xca5a2c = _0x193332 % (0x34dbf ^ 0x34dbb) ? (0xa9b5c ^ 0xa9b1c) * _0xca5a2c + _0x206ef4 : _0x206ef4, _0x193332++ % (0x9df22 ^ 0x9df26)) && (_0x10a753 += String['fromCharCode']((0x486c8 ^ 0x48637) & _0xca5a2c >> (-(0x1c134 ^ 0x1c136) * _0x193332 & (0x58efe ^ 0x58ef8))))) _0x206ef4 = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/='['indexOf'](_0x206ef4);
      for (var _0x2cec6d = 0x8d437 ^ 0x8d437, _0x31750e = _0x10a753['length']; _0x2cec6d < _0x31750e; _0x2cec6d++) _0x9b3c4 += '%' + ("00".split("").reverse().join("") + _0x10a753['charCodeAt'](_0x2cec6d)['toString'](0xc3f6b ^ 0xc3f7b))['slice'](-(0xd286f ^ 0xd286d));
      return decodeURIComponent(_0x9b3c4);
    }, _0x412559 = arguments, a0_0x40fd['HqnvQQ'] = !(0x332c6 ^ 0x332c6));
    var _0x12e38a = _0x12e38a + _0x5ab0ee[0x2dff5 ^ 0x2dff5],
      _0x57c8ec = _0x412559[_0x12e38a];
    return _0x57c8ec ? _0x167b95 = _0x57c8ec : (_0x167b95 = a0_0x40fd['gMESMf'](_0x167b95), _0x412559[_0x12e38a] = _0x167b95), _0x167b95;
  })(_0x412559, _0x3c8930);
}

// 是否 unicode 编码
function isUnicodeEscaped(str) {
    return /\\u[0-9a-fA-F]{4}|\\u\{[0-9a-fA-F]+\}/.test(str);
}


// 1. 预置根目标
const aliasMap = new Map([['a0_0x40fd', true]]);

// 2. 统一的别名解析函数（递归+记忆）
function resolveAlias(name, scope) {
  if (aliasMap.has(name)) return aliasMap.get(name);

  // 变量声明
  const binding = scope.getBinding(name);
  if (binding) {
    const path = binding.path;

    // const x = y
    if (path.isVariableDeclarator() && types.isIdentifier(path.node.init)) {
      const result = resolveAlias(path.node.init.name, path.scope);
      aliasMap.set(name, result);
      return result;
    }

    // 函数参数：function f(p) { ... }
    if (path.isFunction()) {
      // 函数参数本身不可能是别名，除非内部再赋值
      aliasMap.set(name, false);
      return false;
    }
  }

  // 全局作用域下未声明就使用的变量（如 c = xxx）
  // 这里简单返回 false，也可按需求扩展
  aliasMap.set(name, false);
  return false;
}

// 3. 第一次遍历：收集别名
traverse(ast, {
  // 3-a) 变量声明
  VariableDeclarator(path) {
    const { id, init } = path.node;
    if (types.isIdentifier(init)) {
      resolveAlias(id.name, path.scope);
    }
  },

  // 3-b) 赋值表达式
  AssignmentExpression(path) {
    if (path.node.operator !== '=') return;   // 只关心普通 =

    const left = path.node.left;
    const right = path.node.right;

    if (!types.isIdentifier(left)) return;        // 左侧不是简单标识符
    if (!types.isIdentifier(right)) return;       // 右侧也不是简单标识符

    // 右侧指向谁？
    const rightPointsTo = resolveAlias(right.name, path.scope);
    aliasMap.set(left.name, rightPointsTo);
  }
});

// 4. 第二次遍历：处理所有函数调用
traverse(ast, {
  CallExpression(path) {
    const { callee } = path.node;
    if (!types.isIdentifier(callee)) return;

    const pointsTo = resolveAlias(callee.name, path.scope);
    if (pointsTo) {
      // console.log(`Found call: ${path.toString()}`);
      processFunctionCall(path);
    }
  }
});
console.log(aliasMap);  // 调试输出



// 3. 遍历并替换异或表达式
traverse(ast, {
  BinaryExpression(path) {
    const { node } = path;
    if (
      node.operator === '^' &&
      node.left.type === 'NumericLiteral' &&
      node.right.type === 'NumericLiteral'
    ) {
      const result = node.left.value ^ node.right.value;
      path.replaceWith({
        type: 'NumericLiteral',
        value: result
      });
    }
  }
});
function processFunctionCall(path) {
  const { node, scope } = path;
  let { arguments } = node;

  // 确保参数数量在1-2个之间
  if (arguments.length < 1 || arguments.length > 2) {
    return;
  }

  // 计算第一个参数的值
  const firstArgValue = evaluateNode(arguments[0], scope);

  // 如果无法确定第一个参数值，跳过
  if (firstArgValue === undefined) {
    return;
  }

  let secondArgValue = null;
  if (arguments.length === 2) {
    secondArgValue = evaluateNode(arguments[1], scope);
    // 如果第二个参数存在但无法确定值，跳过
    if (secondArgValue === undefined) {
      return;
    }
  }

  // 调用解密函数
  const decryptedValue = a0_0x40fd(firstArgValue, secondArgValue);

  // 用解密后的值替换函数调用
  path.replaceWith({
    type: 'StringLiteral',
    value: decryptedValue
  });
}

// 还原字符串编码
traverse(ast, {
    "StringLiteral": function (path) {
        if (path.node.extra && isUnicodeEscaped(path.node.extra.raw)) {
            // delete path.node.extra.raw
            path.node.extra.raw = "'" + path.node.value + "'"
            // path.node.extra = void 0
        }
    }
})


// 评估AST节点获取其值
function evaluateNode(node, scope) {
    switch (node.type) {
        case 'StringLiteral':
            return node.value;
        case 'NumericLiteral':
            return node.value;
        case 'BooleanLiteral':
            return node.value;
        case 'Identifier':
            // 尝试从作用域中获取变量值
            const binding = scope.getBinding(node.name);
            if (binding && binding.constant && binding.path.node.init) {
                return evaluateNode(binding.path.node.init, scope);
            }
            return undefined;
        case 'BinaryExpression':
            // 处理二进制表达式，如 0x90b99 ^ 0x90f36
            const left = evaluateNode(node.left, scope);
            const right = evaluateNode(node.right, scope);
            if (left === undefined || right === undefined) {
                return undefined;
            }
            switch (node.operator) {
                case '+':
                    return left + right;
                case '-':
                    return left - right;
                case '*':
                    return left * right;
                case '/':
                    return left / right;
                case '%':
                    return left % right;
                case '|':
                    return left | right;
                case '&':
                    return left & right;
                case '^':
                    return left ^ right;  // 异或运算
                case '<<':
                    return left << right;
                case '>>':
                    return left >> right;
                case '>>>':
                    return left >>> right;
                default:
                    return undefined;
            }
        default:
            return undefined;
    }
}


let output = generate(ast).code

fs.writeFileSync("w 反混淆.js", output)